apiVersion: v1
kind: Service
metadata:
  name: airflow-postgres
spec:
  selector:
    app: airflow-postgres
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-postgres
spec:
  selector:
    matchLabels:
      app: airflow-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: airflow-postgres
    spec:
      containers:
      - name: airflow-postgres
        image: postgres:12
        resources:
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: 5432        
        env:
        - name: POSTGRES_PASSWORD
          value: airflow
        - name: POSTGRES_USER
          value: airflow
        - name: POSTGRES_DB
          value: airflow